# Generated by Django 3.2 on 2021-05-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='content',
            new_name='image',
        ),
    ]
